@extends('layouts.main')
@section('title','Γνωρίστε την Ομάδα μας | Επαγγελματική Ομάδα Ιστοσελίδων | DGSolutions')
@section('meta_description', 'Ανακαλύψτε την εμπειρία και το πάθος που χαρακτηρίζει την ομάδα μας στη DGSolutions. Μάθετε για την ιστορία, τις αξίες μας και τον τρόπο με τον οποίο εργαζόμαστε για να προσφέρουμε τις καλύτερες λύσεις στον κόσμο του web development.')
@section('og_title', 'Γνωρίστε την Ομάδα μας | Επαγγελματική Ομάδα Ιστοσελίδων | DGSolutions')
@section('og_url', url()->current())
@section('og_image', 'dsfdsfs')
@section('og_description', 'Ανακαλύψτε την εμπειρία και το πάθος που χαρακτηρίζει την ομάδα μας στη DGSolutions. Μάθετε για την ιστορία, τις αξίες μας και τον τρόπο με τον οποίο εργαζόμαστε για να προσφέρουμε τις καλύτερες λύσεις στον κόσμο του web development.')
@section('content')
@include('partials.about.header')
@include('partials.about.about')
@include('partials.home.cta')
@endsection