@extends('layouts.main')
@section('title','Δείτε τα Έργα μας | Ιστοσελίδες & Eshops | DGSolutions')
@section('meta_description', 'Εξερευνήστε την ποικιλία των έργων ιστοσελίδων και eshops που έχουμε αναπτύξει στη DGSolutions. Δείτε τις καινοτόμες λύσεις και το δημιουργικό μας έργο που κάνει κάθε ιστοσελίδα και eshop μοναδική.')
@section('og_title', 'Δείτε τα Έργα μας | Ιστοσελίδες & Eshops | DGSolutions')
@section('og_url', url()->current())
@section('og_image', 'dsfdsfs')
@section('og_description', 'Εξερευνήστε την ποικιλία των έργων ιστοσελίδων και eshops που έχουμε αναπτύξει στη DGSolutions. Δείτε τις καινοτόμες λύσεις και το δημιουργικό μας έργο που κάνει κάθε ιστοσελίδα και eshop μοναδική.')
@section('content')
@include('partials.portfolio.header')
@include('partials.portfolio.portfolio')
@include('partials.home.cta')
@endsection